import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/content/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        tertiary: '#466500',
        'on-primary-fixed-variant': '#5516be',
        'outline-variant': '#cbc3d7',
        'surface-container': '#e6eeff',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#354e00',
        'inverse-on-surface': '#eaf1ff',
        'error-container': '#ffdad6',
        'on-surface': '#121c2a',
        background: '#f8f9ff',
        'primary-fixed-dim': '#d0bcff',
        'surface-tint': '#6d3bd7',
        'on-tertiary-container': '#faffe8',
        'inverse-surface': '#27313f',
        'on-background': '#121c2a',
        'on-secondary-fixed': '#141b2b',
        'on-primary-container': '#fffbff',
        outline: '#7b7486',
        'on-error': '#ffffff',
        'primary-container': '#8455ef',
        'inverse-primary': '#d0bcff',
        'on-primary': '#ffffff',
        'secondary-container': '#d9dff5',
        'surface-container-high': '#dee9fc',
        'secondary-fixed-dim': '#c0c6db',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'surface-container-highest': '#d9e3f6',
        'tertiary-container': '#598000',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#131f00',
        'tertiary-fixed-dim': '#9fd830',
        surface: '#f8f9ff',
        secondary: '#575e70',
        'surface-variant': '#d9e3f6',
        'on-surface-variant': '#494454',
        'tertiary-fixed': '#baf54c',
        'secondary-fixed': '#dce2f7',
        primary: '#6b38d4',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#d0dbed',
        'surface-container-low': '#eff4ff',
        'on-secondary-container': '#5c6274',
        'on-primary-fixed': '#23005c',
        'on-secondary-fixed-variant': '#404758',
        'primary-fixed': '#e9ddff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'gutter-mobile': '1rem',
        'space-xxs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4.5rem',
        'space-4xl': '6rem',
        'gutter-desktop': '2rem',
        'container-max': '1360px',
        // Legacy aliases
        'section-gap': '6rem',
        'card-padding-lg': '2.5rem',
        'card-padding-sm': '1.25rem',
        'grid-gutter-sm': '1rem',
        'grid-gutter-lg': '2rem',
        'grid-gutter-md': '1.5rem',
        'margin-desktop': '4rem',
        'card-padding-md': '1.75rem',
        'margin-mobile': '1.25rem',
        'margin-tablet': '2.5rem',
      },
      fontFamily: {
        sans: ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'headline-sm': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'body-md': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'headline-md': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'display-hero': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'label-md': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'label-sm': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'headline-lg': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'body-lg': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'body-sm': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'display-hero-mobile': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'label-code': ['var(--font-space-grotesk)', 'Space Grotesk', 'monospace'],
        'label-badge': ['var(--font-sora)', 'Sora', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-hero': ['64px', { lineHeight: '72px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-lg': ['44px', { lineHeight: '52px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.005em', fontWeight: '400' }],
        'display-hero-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

export default config;
